### PR TITLE
Extends keyboard support to easily handle multiple trigger keys

### PR DESCRIPTION
**Pull request by marksherman**
Extends and supplants #5 (with proper accreditation, nice job, @keheitz).
Solves #1 .

### CODE REVIEW

**Comment by beckyconning** [comment]
these key codes aren't necessarily the same in each region btw.

try using [DOM Level 3 KeyboardEvent.key](http://www.w3.org/TR/DOM-Level-3-Events-key/) instead.

there is a polyfill here: https://github.com/inexorabletash/polyfill/blob/master/keyboard.md

**Comment by beckyconning** [comment]
those arrow key codes should be okay in most places but to be safe i normally use [DOM Level 3 `KeyboardEvent.code`](http://www.w3.org/TR/DOM-Level-3-Events-code/).

**Comment by beckyconning** [comment]
oh i didn't notice the e.which, that might solve it, i'm not a big jquery user.

**Comment by cathydeng** [comment]
hey @marksherman, I'm gona stick w/ keeping this simple/clear; I don't see a clear advantage to having multiple keyboard shortcuts. thanks though!

**Comment by marksherman** [comment]
👍

**Pull request closed without merging**
